DELIMITER $$
CREATE TRIGGER `ADD_DETAILS` AFTER INSERT ON `temporals` FOR EACH ROW INSERT INTO DETALLE_SERVICIOS (ID, URL_IMAGEN,DESCUENTO,TOTAL,DESCRIPCION,SERVICIOS_ID)
VALUES(NEW.ID, NEW.URL_IMAGEN,NEW.DESCUENTO,0, NEW.DESCRIPCION,NEW.ID)
$$
DELIMITER ;
DELIMITER $$
CREATE TRIGGER `ADD_SERVICES` AFTER INSERT ON `temporals` FOR EACH ROW INSERT INTO SERVICIOS (ID,NOMBRE, SEXO, CANTIDAD_MIN_SESION,CANTIDAD_MAX_SESION, PRECIO_MIN_SESION,PRECIO_MAX_SESION,ZONAS,TIPO_ID)
VALUES(NEW.ID, NEW.NOMBRE,NEW.SEXO,NEW.CANTIDAD_MIN_SESION, NEW.CANTIDAD_MAX_SESION, NEW.PRECIO_MIN_SESION, NEW.PRECIO_MAX_SESION,NEW.ZONAS,NEW.TIPO_ID)
$$
DELIMITER ;